### ISSUE TITLE
iconv fails for conversion _from_ non ASCII when run under _bash_

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/libiconvport#12] opened 2023-04-06 23:04 UTC
works fine when run under the standard shell.
@IgorTodorovskiIBM not sure if this is a bash bug, an iconv bug, a zoslib bug, or some combination of all of these.

**Comment by MikeFultonDev** [comment] 2023-04-06 23:04
@perry-ca @zsw007 fya

**Comment by perry-ca** [comment] 2023-04-10 00:10
I think the problem is the `_TAG_REDIR_xxx` env vars.  I'm pretty sure they are causing the output from iconv to be mapped to ascii and then written to a file tagged with 819.  I had opened an issue to remove the setting of these env vars and `_CEE_RUNOPTS` from the `.env` file.  The user should be deciding if they want auto conversion or not.

**Comment by IgorTodorovskiIBM** [comment] 2023-04-10 16:23
Is this related? This is generating an unreadable  ISO8859-1 file in sh and bash:
```
touch 1047.txt && chtag -tc 1047 1047.txt
echo "HELLO WORLD" > 1047.txt
iconv -f IBM-1047 -t ISO8859-1 1047.txt > 819.txt
cat 819.txt
```
I get this:
```
��<<|��|�<�[\u@\h \w]$
```

We may want to disable auto-conversion in iconv.

**Comment by perry-ca** [comment] 2023-04-10 16:28
Do you have the _TAG_REDIR env vars set?  Also is the contents of 1047.txt correct to begin with?  I wonder if the redirect is translating the 1047 into 819 so now the contents and tagging don't match.

**Comment by IgorTodorovskiIBM** [comment] 2023-04-10 16:34
> Do you have the _TAG_REDIR env vars set? Also is the contents of 1047.txt correct to begin with? I wonder if the redirect is translating the 1047 into 819 so now the contents and tagging don't match.

The 1047.txt file is readable and tagged as IBM-1047. I tried with and without _TAG_REDIR environment variables. I think the issue is that it's double converted, once from USS and then again from iconv.

**Comment by gngrossi** [comment] 2023-04-28 13:29
any update?
thanks

**Comment by IgorTodorovskiIBM** [comment] 2023-04-28 14:03
The IBM-1047 iconv issue should be resolved with https://github.com/ZOSOpenTools/libiconvport/pull/13. @MikeFultonDev , can you confirm or were there others issues as well?

**Comment by MikeFultonDev** [comment] 2023-04-28 14:17
Nice!

Yep - just checked it:

```
FULTONM@ZOSCAN2B bash ~/zopen/dev> type -a iconv
iconv is /bin/iconv
FULTONM@ZOSCAN2B bash ~/zopen/dev> cd ../prod/libiconv
FULTONM@ZOSCAN2B bash ~/zopen/prod/libiconv> . ./.env
Setting up libiconv...
Setup completed.
FULTONM@ZOSCAN2B bash ~/zopen/prod/libiconv> type -a iconv
iconv is /home/fultonm/zopen/prod/libiconv/bin/iconv
iconv is /bin/iconv
FULTONM@ZOSCAN2B bash ~/zopen/prod/libiconv> cd /tmp
FULTONM@ZOSCAN2B bash /tmp> vi my.text
FULTONM@ZOSCAN2B bash /tmp> ls -T my.text
t ISO8859-1   T=on  my.text
FULTONM@ZOSCAN2B bash /tmp> iconv -f ISO-8859-1 -t IBM-1047 <my.text >my.ebcdic
FULTONM@ZOSCAN2B bash /tmp> vi my.ebcdic
FULTONM@ZOSCAN2B bash /tmp> ls -T my.ebcdic
t IBM-1047    T=on  my.ebcdic
FULTONM@ZOSCAN2B bash /tmp> cat my.ebcdic
This is a file
FULTONM@ZOSCAN2B bash /tmp> cat my.text
This is a file
FULTONM@ZOSCAN2B bash /tmp>
```

**Comment by gngrossi** [comment] 2023-04-28 14:38
Trying Igor's use case...what am I missing?
thanks

RC=(0) [SYSA] bash-5.2$ touch 1047.txt && chtag -tc 1047 1047.txt
RC=(0) [SYSA] bash-5.2$ echo "HELLO WORLD" > 1047.txt
RC=(0) [SYSA] bash-5.2$ iconv -f IBM-1047 -t ISO8859-1 1047.txt > 819.txt
RC=(127) [SYSA] bash-5.2$ ls -T
t IBM-1047    T=on  1047.txt
t ISO8859-1   T=on  819.txt

RC=(0) [SYSA] bash-5.2$ diff 1047* 819*
1c1
< HELLO WORLD
---
> ▒▒<<|▒▒|▒<▒
\ No newline at end of file

RC=(1) [SYSA] bash-5.2$ cat 819*
▒▒<<|▒▒|▒<▒RC=(0) [SYSA] bash-5.2$

**Comment by MikeFultonDev** [comment] 2023-04-28 15:11
Re-opening. I tested the wrong direction. @IgorTodorovskiIBM can you investigate?

**Comment by IgorTodorovskiIBM** [comment] 2023-04-28 15:18
Turns out we haven't had a successful build in 3 weeks. The patch was merged in 2 weeks ago, I'll investigate.

**Comment by MikeFultonDev** [comment] 2023-05-01 22:49
@IgorTodorovskiIBM I tried this with the bash build: 
```
zopen install bash
- z/OS Open Tools configuration completed in 0 seconds.
- z/OS Open Tools configuration completed in 0 seconds.
***WARNING: Setting ZOPEN_GITHUB_OAUTH_TOKEN is recommended to ensure that you do not hit the GitHub API cap. See --help for more details.
Checking bash...
New release with tag "Releaseline_bashport_967" found for bashport
Preparing to download bash
Downloading latest release from bashport...
Extracting bash-5.2.15.20230429_231209.zos.pax.Z...
Setting up bash...
Setup completed.
```

and it's still busted for conversion from IBM-1047 to iso-8859-1 

Can you investigate?

**Comment by IgorTodorovskiIBM** [comment] 2023-05-02 23:09
The latest release has the fix - https://github.com/ZOSOpenTools/libiconvport/releases/tag/Releaseline_libiconvport_978

**Comment by gngrossi** [comment] 2023-05-03 15:09
Looks good...thanks

**Closed as completed** 2023-05-17 16:24 UTC
Labels: bug
